from pathlib import Path
import json
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier

BASE = Path(__file__).resolve().parents[1]
DATA = BASE / "data" / "ml_training_dataset.csv"
MODEL_DIR = BASE / "models"
MODEL_DIR.mkdir(exist_ok=True)

HORIZONS = [6, 12, 24]

DROP = {
    "timestamp",
    "location_id",
    "location_name",
    "latitude",
    "longitude",
    "forecast_rainfall_mm",
    "forecast_rain_1h",
    "forecast_rain_3h",
    "forecast_rain_6h",
    "target_hazard_6h",
    "target_hazard_12h",
    "target_hazard_24h",
}

RAIN_COLS = [
    "rainfall_mm",
    "rain_1h",
    "rain_3h",
    "rain_6h",
    "rain_12h",
    "rain_24h",
    "rain_48h",
]

SOIL_COLS = [
    "soil_moisture_0_7cm",
    "soil_moisture_7_28cm",
    "soil_moisture_28_100cm",
    "soil_moisture_100_255cm",
]


def make_synthetic_positive_samples(base_rows, n_samples, rng):
    """Create transparent prototype positive scenarios from real positives."""
    if base_rows.empty or n_samples <= 0:
        return pd.DataFrame(columns=base_rows.columns)

    rows = []

    for _ in range(n_samples):
        base = base_rows.iloc[rng.integers(0, len(base_rows))].copy()

        # Keep the original prototype augmentation idea, but use a
        # somewhat wider controlled range around observed event patterns.
        multiplier = float(rng.uniform(0.85, 2.75))

        for col in RAIN_COLS:
            value = pd.to_numeric(base[col], errors="coerce")

            if pd.notna(value):
                jitter = float(rng.uniform(0.92, 1.08))
                base[col] = max(
                    0.0,
                    float(value) * multiplier * jitter,
                )

        for col in SOIL_COLS:
            value = pd.to_numeric(base[col], errors="coerce")

            if pd.notna(value):
                base[col] = max(
                    0.0,
                    float(value) * float(rng.uniform(0.85, 1.12)),
                )

        rows.append(base)

    return pd.DataFrame(rows, columns=base_rows.columns)


def build_monotonic_constraints(feature_cols):
    """
    Rainfall is monotonic-positive.

    For the same soil/terrain conditions, increasing any rainfall
    accumulation feature cannot decrease the model hazard score.

    Soil and terrain are left unconstrained so the model can still
    learn their contextual effects.
    """
    return [
        1 if column in RAIN_COLS else 0
        for column in feature_cols
    ]


def main():
    print(f"Loading {DATA}")

    d = pd.read_csv(DATA)

    d["timestamp"] = pd.to_datetime(
        d["timestamp"],
        errors="coerce",
    )

    d = (
        d.sort_values("timestamp")
        .reset_index(drop=True)
    )

    feature_cols = [
        column
        for column in d.columns
        if (
            column not in DROP
            and pd.api.types.is_numeric_dtype(d[column])
        )
    ]

    d = (
        d.dropna(subset=feature_cols)
        .reset_index(drop=True)
    )

    print(f"Rows: {len(d):,}")
    print(
        f"Features ({len(feature_cols)}): "
        f"{feature_cols}"
    )

    monotonic_constraints = build_monotonic_constraints(
        feature_cols
    )

    print("\nMonotonic constraints:")
    for column, constraint in zip(
        feature_cols,
        monotonic_constraints,
    ):
        label = (
            "INCREASING"
            if constraint == 1
            else "unconstrained"
        )
        print(f"  {column}: {label}")

    summary = {
        "status": "prototype",
        "dataset_rows": int(len(d)),
        "feature_columns": feature_cols,
        "excluded_forecast_features": True,
        "models": {},
        "model_type": "HistGradientBoostingClassifier",
        "monotonic_constraints": {
            column: (
                "increasing"
                if constraint == 1
                else "unconstrained"
            )
            for column, constraint in zip(
                feature_cols,
                monotonic_constraints,
            )
        },
        "augmentation": {
            "enabled": True,
            "method": (
                "Synthetic positive scenarios generated by "
                "perturbing real event-positive rows. Rainfall "
                "is intensified and soil moisture is varied."
            ),
            "warning": (
                "Synthetic positives are prototype augmentation "
                "only. They are not independently observed "
                "disaster labels."
            ),
        },
        "warning": (
            "Prototype only. Positive labels include a small "
            "number of documented disaster-event samples plus "
            "transparent synthetic scenario augmentation. "
            "Outputs are not calibrated real-world probabilities "
            "and are not independently validated."
        ),
    }

    rng = np.random.default_rng(42)

    for h in HORIZONS:
        target = f"target_hazard_{h}h"

        y_base = d[target].astype(int)

        positives = int(y_base.sum())
        negatives = int((y_base == 0).sum())

        print("\n" + "=" * 70)
        print(f"TRAINING {h}H MONOTONIC PROTOTYPE")
        print("=" * 70)
        print(f"Real positive samples: {positives}")
        print(f"Available negative samples: {negatives}")

        if positives == 0:
            print("SKIPPED: no positive samples.")

            summary["models"][str(h)] = {
                "status": "skipped"
            }

            continue

        synthetic_count = min(
            max(600, positives * 50),
            1500,
        )

        positive_rows = d.loc[
            y_base == 1,
            feature_cols,
        ].copy()

        synthetic = make_synthetic_positive_samples(
            positive_rows,
            synthetic_count,
            rng,
        )

        positive_train = pd.concat(
            [
                positive_rows,
                synthetic,
            ],
            ignore_index=True,
        )

        negative_pool = d.loc[
            y_base == 0,
            feature_cols,
        ].copy()

        negative_count = min(
            len(negative_pool),
            max(
                len(positive_train) * 4,
                5000,
            ),
        )

        negative_train = negative_pool.sample(
            n=negative_count,
            random_state=42 + h,
        )

        X_train = pd.concat(
            [
                positive_train,
                negative_train,
            ],
            ignore_index=True,
        )

        y_train = pd.Series(
            [1] * len(positive_train)
            + [0] * len(negative_train),
            name=target,
        )

        order = rng.permutation(
            len(X_train)
        )

        X_train = (
            X_train.iloc[order]
            .reset_index(drop=True)
        )

        y_train = (
            y_train.iloc[order]
            .reset_index(drop=True)
        )

        print(
            f"Training positives: "
            f"{len(positive_train):,} "
            f"(real {len(positive_rows):,}, "
            f"synthetic {len(synthetic):,})"
        )

        print(
            f"Training negatives: "
            f"{len(negative_train):,}"
        )

        # HistGradientBoosting supports monotonic constraints.
        # Positive rainfall constraints make the simulation curve
        # physically/intuitively consistent for increasing rainfall.
        model = HistGradientBoostingClassifier(
            learning_rate=0.08,
            max_iter=300,
            max_leaf_nodes=31,
            max_depth=None,
            min_samples_leaf=20,
            l2_regularization=1.0,
            random_state=42 + h,
            monotonic_cst=monotonic_constraints,
        )

        model.fit(
            X_train,
            y_train,
        )

        model_path = (
            MODEL_DIR
            / f"flash_flood_rf_{h}h.joblib"
        )

        joblib.dump(
            {
                "model": model,
                "feature_columns": feature_cols,
                "horizon_hours": h,
                "training_rows": int(len(X_train)),
                "real_positive_samples": int(
                    len(positive_rows)
                ),
                "synthetic_positive_samples": int(
                    len(synthetic)
                ),
                "positive_samples": int(
                    len(positive_train)
                ),
                "negative_samples": int(
                    len(negative_train)
                ),
                "model_type":
                    "HistGradientBoostingClassifier",
                "feature_policy":
                    "Observed rainfall + soil moisture + "
                    "terrain only. Future ECMWF forecast is "
                    "handled by V4 forecast risk.",
                "monotonic_rainfall_features": RAIN_COLS,
                "prototype_only": True,
                "synthetic_augmentation": True,
                "probability_calibrated": False,
                "validation_status":
                    "Not independently validated.",
            },
            model_path,
        )

        print(f"Saved: {model_path}")

        # HistGradientBoosting does not expose RF feature_importances_.
        # Keep training metadata explicit instead.
        summary["models"][str(h)] = {
            "status": "trained",
            "model_path": str(model_path),
            "training_rows": int(len(X_train)),
            "real_positive_samples": int(
                len(positive_rows)
            ),
            "synthetic_positive_samples": int(
                len(synthetic)
            ),
            "positive_samples": int(
                len(positive_train)
            ),
            "negative_samples": int(
                len(negative_train)
            ),
            "model_type":
                "HistGradientBoostingClassifier",
            "monotonic_rainfall_features": RAIN_COLS,
            "probability_calibrated": False,
            "validation_status":
                "Not independently validated.",
        }

    summary_path = (
        MODEL_DIR
        / "training_summary.json"
    )

    summary_path.write_text(
        json.dumps(
            summary,
            indent=2,
        ),
        encoding="utf-8",
    )

    print("\n" + "=" * 70)
    print("MONOTONIC ML PROTOTYPE TRAINING COMPLETE")
    print("=" * 70)
    print(f"Models saved to: {MODEL_DIR}")
    print(f"Summary saved to: {summary_path}")


if __name__ == "__main__":
    main()
